[pytest]
addopts = -v --tb=short --alluredir=allure-results --clean-alluredir --html=report.html --self-contained-html --reruns 1 --reruns-delay 2
testpaths = testslog_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S


